package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"errors"
	"fmt"

	api "github.com/photoview/photoview/api/graphql"
	"github.com/photoview/photoview/api/graphql/auth"
	"github.com/photoview/photoview/api/graphql/models"
	"github.com/photoview/photoview/api/graphql/models/actions"
	"gorm.io/gorm"
)

// Media is the resolver for the media field.
func (r *albumResolver) Media(ctx context.Context, obj *models.Album, order *models.Ordering, paginate *models.Pagination, onlyFavorites *bool) ([]*models.Media, error) {
	db := r.DB(ctx)

	query := db.
		Where("media.album_id = ?", obj.ID).
		Where("media.id IN (?)", db.Model(&models.MediaURL{}).
			Select("media_urls.media_id").
			Where("media_urls.media_id = media.id"))

	if onlyFavorites != nil && *onlyFavorites == true {
		user := auth.UserFromContext(ctx)
		if user == nil {
			return nil, errors.New("cannot get favorite media without being authorized")
		}

		favoriteQuery := db.Model(&models.UserMediaData{
			UserID: user.ID,
		}).Where("user_media_data.media_id = media.id").Where("user_media_data.favorite = true")

		query = query.Where("EXISTS (?)", favoriteQuery)
	}

	query = models.FormatSQL(query, order, paginate)

	var media []*models.Media
	if err := query.Find(&media).Error; err != nil {
		return nil, err
	}

	return media, nil
}

// SubAlbums is the resolver for the subAlbums field.
func (r *albumResolver) SubAlbums(ctx context.Context, obj *models.Album, order *models.Ordering, paginate *models.Pagination) ([]*models.Album, error) {
	var albums []*models.Album

	query := r.DB(ctx).Where("parent_album_id = ?", obj.ID)
	query = models.FormatSQL(query, order, paginate)

	if err := query.Find(&albums).Error; err != nil {
		return nil, err
	}

	return albums, nil
}

// Owner is the resolver for the owner field.
func (r *albumResolver) Owner(ctx context.Context, obj *models.Album) (*models.User, error) {
	panic("not implemented")
}

// Thumbnail is the resolver for the thumbnail field.
func (r *albumResolver) Thumbnail(ctx context.Context, obj *models.Album) (*models.Media, error) {
	return obj.Thumbnail(r.DB(ctx))
}

// Path is the resolver for the path field.
func (r *albumResolver) Path(ctx context.Context, obj *models.Album) ([]*models.Album, error) {
	user := auth.UserFromContext(ctx)
	if user == nil {
		empty := make([]*models.Album, 0)
		return empty, nil
	}

	return actions.AlbumPath(r.DB(ctx), user, obj)
}

// Shares is the resolver for the shares field.
func (r *albumResolver) Shares(ctx context.Context, obj *models.Album) ([]*models.ShareToken, error) {
	var shareTokens []*models.ShareToken
	if err := r.DB(ctx).Where("album_id = ?", obj.ID).Find(&shareTokens).Error; err != nil {
		return nil, err
	}

	return shareTokens, nil
}

// Takes album_id, resets album.cover_id to 0 (null)
func (r *mutationResolver) ResetAlbumCover(ctx context.Context, albumID int) (*models.Album, error) {
	user := auth.UserFromContext(ctx)
	if user == nil {
		return nil, errors.New("unauthorized")
	}

	return actions.ResetAlbumCover(r.DB(ctx), user, albumID)
}

// SetAlbumCover is the resolver for the setAlbumCover field.
func (r *mutationResolver) SetAlbumCover(ctx context.Context, coverID int) (*models.Album, error) {
	user := auth.UserFromContext(ctx)
	if user == nil {
		return nil, errors.New("unauthorized")
	}

	return actions.SetAlbumCover(r.DB(ctx), user, coverID)
}

// MyAlbums is the resolver for the myAlbums field.
func (r *queryResolver) MyAlbums(ctx context.Context, order *models.Ordering, paginate *models.Pagination, onlyRoot *bool, showEmpty *bool, onlyWithFavorites *bool) ([]*models.Album, error) {
	user := auth.UserFromContext(ctx)
	if user == nil {
		return nil, auth.ErrUnauthorized
	}

	return actions.MyAlbums(r.DB(ctx), user, order, paginate, onlyRoot, showEmpty, onlyWithFavorites)
}

// Album is the resolver for the album field.
func (r *queryResolver) Album(ctx context.Context, id int, tokenCredentials *models.ShareTokenCredentials) (*models.Album, error) {
	db := r.DB(ctx)
	if tokenCredentials != nil {

		shareToken, err := r.ShareToken(ctx, *tokenCredentials)
		if err != nil {
			return nil, err
		}

		if shareToken.Album != nil {
			if *shareToken.AlbumID == id {
				return shareToken.Album, nil
			}

			subAlbum, err := shareToken.Album.GetChildren(db, func(query *gorm.DB) *gorm.DB {
				return query.Where("sub_albums.id = ?", id)
			})
			if err != nil {
				return nil, fmt.Errorf("find sub album of share token (%s): %w", tokenCredentials.Token, err)
			}

			if len(subAlbum) > 0 {
				return subAlbum[0], nil
			}
		}
	}

	user := auth.UserFromContext(ctx)
	if user == nil {
		return nil, auth.ErrUnauthorized
	}

	return actions.Album(db, user, id)
}

// maxAlbumTreeChildrenIDs bounds one albumTreeChildren request. The ids come
// from the client, and the filter view sends every match plus its ancestors
// with no search limit, so a broad match against a large library could
// otherwise build an IN clause past the database driver's parameter limit. A
// tree with this many visible nodes is beyond useful anyway.
const maxAlbumTreeChildrenIDs = 500

// AlbumTreeChildren is the resolver for the albumTreeChildren field.
func (r *queryResolver) AlbumTreeChildren(ctx context.Context, albumIds []int) ([]*models.AlbumTreeChildren, error) {
	db := r.DB(ctx)

	if len(albumIds) == 0 {
		return []*models.AlbumTreeChildren{}, nil
	}

	if len(albumIds) > maxAlbumTreeChildrenIDs {
		return nil, fmt.Errorf("too many albums requested at once (%d, limit %d)", len(albumIds), maxAlbumTreeChildrenIDs)
	}

	user := auth.UserFromContext(ctx)
	if user == nil {
		return nil, auth.ErrUnauthorized
	}

	// Unlike the subAlbums field resolver, which is only reachable through an
	// album the caller was already authorized to load, this takes raw ids
	// straight from the client - so the parents are authorized here, and
	// their children then follow as they do for subAlbums.
	authorizedIDs, err := r.authorizedAlbumIDs(ctx, user, albumIds)
	if err != nil {
		return nil, err
	}

	byParent := make(map[int][]*models.Album, len(authorizedIDs))

	if len(authorizedIDs) > 0 {
		var albums []*models.Album

		orderByTitle := "title"
		query := models.FormatSQL(
			db.Where("parent_album_id IN (?)", authorizedIDs),
			&models.Ordering{OrderBy: &orderByTitle}, nil)

		if err := query.Find(&albums).Error; err != nil {
			return nil, err
		}

		for _, album := range albums {
			if album.ParentAlbumID == nil {
				continue
			}

			byParent[*album.ParentAlbumID] = append(byParent[*album.ParentAlbumID], album)
		}
	}

	result := make([]*models.AlbumTreeChildren, len(albumIds))
	for i, albumID := range albumIds {
		result[i] = &models.AlbumTreeChildren{
			AlbumID:  albumID,
			Children: byParent[albumID],
		}
	}

	return result, nil
}

// authorizedAlbumIDs narrows albumIds to the ones user may see. Access is
// inherited, so a direct user_albums row is the common case but not the only
// one: a user linked only to a root album owns everything below it. The set
// lookup answers the common case without a query per album, and only the ids
// it misses fall back to the ancestor walk OwnsAlbum performs.
func (r *queryResolver) authorizedAlbumIDs(ctx context.Context, user *models.User, albumIds []int) ([]int, error) {
	if user.Admin {
		return albumIds, nil
	}

	db := r.DB(ctx)

	var directIDs []int
	if err := db.Table("user_albums").
		Where("user_id = ? AND album_id IN (?)", user.ID, albumIds).
		Pluck("album_id", &directIDs).Error; err != nil {
		return nil, err
	}

	direct := make(map[int]struct{}, len(directIDs))
	for _, id := range directIDs {
		direct[id] = struct{}{}
	}

	authorized := make([]int, 0, len(albumIds))

	for _, albumID := range albumIds {
		if _, found := direct[albumID]; found {
			authorized = append(authorized, albumID)

			continue
		}

		var album models.Album
		if err := db.First(&album, albumID).Error; err != nil {
			if errors.Is(err, gorm.ErrRecordNotFound) {
				continue
			}

			return nil, err
		}

		owns, err := user.OwnsAlbum(db, &album)
		if err != nil {
			return nil, err
		}

		if owns {
			authorized = append(authorized, albumID)
		}
	}

	return authorized, nil
}

// Album returns api.AlbumResolver implementation.
func (r *Resolver) Album() api.AlbumResolver { return &albumResolver{r} }

type albumResolver struct{ *Resolver }
